//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Product_Info = new HashSet<Product_Info>();
            this.Sub_Category = new HashSet<Sub_Category>();
        }
    
        public int category_id { get; set; }
        public string category_name { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> active_flag { get; set; }
    
        public virtual ICollection<Product_Info> Product_Info { get; set; }
        public virtual ICollection<Sub_Category> Sub_Category { get; set; }
    }
}
