//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Info
    {
        public Product_Info()
        {
            this.Product_Purchase = new HashSet<Product_Purchase>();
            this.Product_Sales = new HashSet<Product_Sales>();
        }
    
        public int product_info_id { get; set; }
        public string product_desc { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> sub_category_id { get; set; }
        public Nullable<double> product_orig_price { get; set; }
        public Nullable<double> product_sold_price { get; set; }
        public Nullable<int> unit_id { get; set; }
        public string product_code { get; set; }
        public Nullable<double> product_qty { get; set; }
        public Nullable<double> product_cut_off { get; set; }
        public string product_remarks { get; set; }
        public Nullable<int> supplier_info_id { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public bool active_flag { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Staff_Info Staff_Info { get; set; }
        public virtual Staff_Info Staff_Info1 { get; set; }
        public virtual ICollection<Product_Purchase> Product_Purchase { get; set; }
        public virtual ICollection<Product_Sales> Product_Sales { get; set; }
        public virtual Sub_Category Sub_Category { get; set; }
        public virtual Supplier_Info Supplier_Info { get; set; }
    }
}
