//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Info_vw
    {
        public int product_info_id { get; set; }
        public string product_desc { get; set; }
        public string category_name { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> sub_category_id { get; set; }
        public string sub_category_name { get; set; }
        public Nullable<double> product_orig_price { get; set; }
        public Nullable<double> product_sold_price { get; set; }
        public Nullable<int> unit_id { get; set; }
        public string unit_code { get; set; }
        public string unit_name { get; set; }
        public string product_code { get; set; }
        public Nullable<double> product_qty { get; set; }
        public Nullable<double> product_cut_off { get; set; }
        public string product_remarks { get; set; }
        public string supplier_name { get; set; }
        public string created_fname { get; set; }
        public string created_lname { get; set; }
        public string updated_fname { get; set; }
        public string updated_lname { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public bool active_flag { get; set; }
        public string complete_info { get; set; }
    }
}
