//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Transactions
    {
        public Purchase_Transactions()
        {
            this.Product_Purchase = new HashSet<Product_Purchase>();
        }
    
        public int pt_id { get; set; }
        public string purchase_name { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<System.DateTime> expected_date { get; set; }
        public string status { get; set; }
        public Nullable<int> order_by { get; set; }
    
        public virtual ICollection<Product_Purchase> Product_Purchase { get; set; }
        public virtual Supplier_Info Supplier_Info { get; set; }
        public virtual Staff_Info Staff_Info { get; set; }
    }
}
