//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Info
    {
        public Staff_Info()
        {
            this.Deliveries = new HashSet<Delivery>();
            this.Expenses = new HashSet<Expens>();
            this.Expenses1 = new HashSet<Expens>();
            this.Product_Info = new HashSet<Product_Info>();
            this.Product_Info1 = new HashSet<Product_Info>();
            this.Product_Sales = new HashSet<Product_Sales>();
            this.Purchase_Transactions = new HashSet<Purchase_Transactions>();
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int staff_id { get; set; }
        public string staff_fname { get; set; }
        public string staff_lname { get; set; }
        public Nullable<int> account_info_id { get; set; }
        public Nullable<double> staff_monthly_paid { get; set; }
        public Nullable<bool> active_flag { get; set; }
    
        public virtual Account_Info Account_Info { get; set; }
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual ICollection<Expens> Expenses1 { get; set; }
        public virtual ICollection<Product_Info> Product_Info { get; set; }
        public virtual ICollection<Product_Info> Product_Info1 { get; set; }
        public virtual ICollection<Product_Sales> Product_Sales { get; set; }
        public virtual ICollection<Purchase_Transactions> Purchase_Transactions { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
