//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Info
    {
        public Supplier_Info()
        {
            this.Product_Info = new HashSet<Product_Info>();
            this.Purchase_Transactions = new HashSet<Purchase_Transactions>();
        }
    
        public int supplier_info_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_contact_info { get; set; }
        public string supplier_contact_person { get; set; }
        public string supplier_address { get; set; }
        public string company_name { get; set; }
        public Nullable<bool> active_flag { get; set; }
    
        public virtual ICollection<Product_Info> Product_Info { get; set; }
        public virtual ICollection<Purchase_Transactions> Purchase_Transactions { get; set; }
    }
}
