//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Info
    {
        public Account_Info()
        {
            this.Staff_Info = new HashSet<Staff_Info>();
            this.System_Menu_Roles = new HashSet<System_Menu_Roles>();
        }
    
        public int account_info_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string user_type { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public Nullable<bool> login { get; set; }
    
        public virtual ICollection<Staff_Info> Staff_Info { get; set; }
        public virtual ICollection<System_Menu_Roles> System_Menu_Roles { get; set; }
    }
}
