//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int delivery_id { get; set; }
        public Nullable<int> receipt_id { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string customer_location { get; set; }
        public Nullable<int> delivery_route { get; set; }
        public string customer_contact { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> active_flag { get; set; }
    
        public virtual Staff_Info Staff_Info { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
