//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_OrderedList_vw
    {
        public int pt_id { get; set; }
        public string purchase_name { get; set; }
        public Nullable<System.DateTime> expected_date { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public string status { get; set; }
        public string supplier_name { get; set; }
        public string staff_fname { get; set; }
        public string staff_lname { get; set; }
        public Nullable<double> totalPT { get; set; }
        public Nullable<int> no_item { get; set; }
    }
}
