//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reff_Out_Of_Stock_vw
    {
        public int product_purchase_id { get; set; }
        public Nullable<int> product_info_id { get; set; }
        public Nullable<double> purchase_qty { get; set; }
        public Nullable<double> purchase_new_price { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public Nullable<int> pt_id { get; set; }
    }
}
