//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sis_dbEntities : DbContext
    {
        public sis_dbEntities()
            : base("name=sis_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account_Info> Account_Info { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Delivery> Deliveries { get; set; }
        public DbSet<Expens> Expenses { get; set; }
        public DbSet<Product_Info> Product_Info { get; set; }
        public DbSet<Product_Purchase> Product_Purchase { get; set; }
        public DbSet<Product_Sales> Product_Sales { get; set; }
        public DbSet<Purchase_Transactions> Purchase_Transactions { get; set; }
        public DbSet<Receipt> Receipts { get; set; }
        public DbSet<Staff_Info> Staff_Info { get; set; }
        public DbSet<Sub_Category> Sub_Category { get; set; }
        public DbSet<Supplier_Info> Supplier_Info { get; set; }
        public DbSet<System_Menu_Roles> System_Menu_Roles { get; set; }
        public DbSet<System_Menus> System_Menus { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<Current_Order_Items> Current_Order_Items { get; set; }
        public DbSet<Expenses_Type_vw> Expenses_Type_vw { get; set; }
        public DbSet<Out_Of_Stock_Transactions_vw> Out_Of_Stock_Transactions_vw { get; set; }
        public DbSet<Out_Of_Stock_vw> Out_Of_Stock_vw { get; set; }
        public DbSet<Product_Info_vw> Product_Info_vw { get; set; }
        public DbSet<PT_OrderedList_vw> PT_OrderedList_vw { get; set; }
        public DbSet<Purchase_Transactions_vw> Purchase_Transactions_vw { get; set; }
        public DbSet<Reff_Out_Of_Stock_vw> Reff_Out_Of_Stock_vw { get; set; }
    }
}
