//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Menu_Roles
    {
        public int system_menu_roles_id { get; set; }
        public Nullable<int> account_info_id { get; set; }
        public Nullable<int> system_menus_id { get; set; }
        public Nullable<bool> active_flag { get; set; }
    
        public virtual Account_Info Account_Info { get; set; }
        public virtual System_Menus System_Menus { get; set; }
    }
}
